#텍스트 유사도
텍스트가 얼마나 유사한지 표현하는 방식 중 하나다.   
다양한 측정 방법이 있고 방법에 따라 유사도가 크게 달라질 수 있으므로 의도하고자 하는 방향에 맞는 유사도 측정 방법을 고르는 것이 중요하다

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pprint

TF-IDF 를 통해 벡터화한다.

In [2]:
sent = ("휴일 인 오늘 도 서쪽 을 중심 으로 폭염이 이어졌는데요, 내일 은 반가운 비 소식이 있습니다.", 
        "폭염 을 피해서 휴일 에 놀러왔다가 갑작스런 비 로 인해 망연자실 하고 있습니다.")

tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(sent)

idf = tfidf_vectorizer.idf_

In [5]:
pprint.pprint(dict(zip(tfidf_vectorizer.get_feature_names(), idf)))

{'갑작스런': 1.4054651081081644,
 '내일': 1.4054651081081644,
 '놀러왔다가': 1.4054651081081644,
 '망연자실': 1.4054651081081644,
 '반가운': 1.4054651081081644,
 '서쪽': 1.4054651081081644,
 '소식이': 1.4054651081081644,
 '오늘': 1.4054651081081644,
 '으로': 1.4054651081081644,
 '이어졌는데요': 1.4054651081081644,
 '인해': 1.4054651081081644,
 '있습니다': 1.0,
 '중심': 1.4054651081081644,
 '폭염': 1.4054651081081644,
 '폭염이': 1.4054651081081644,
 '피해서': 1.4054651081081644,
 '하고': 1.4054651081081644,
 '휴일': 1.0}


코사인 유사도 측정으로 첫 번째와 두 번째 문장 비교

In [6]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:2])

array([[0.11304078]])

유클리디언 유사도 측정으로 첫 번쨰와 두 번쨰 문장 비교

In [7]:
from sklearn.metrics.pairwise import euclidean_distances

euclidean_distances(tfidf_matrix[0:1], tfidf_matrix[1:2])

array([[1.33188529]])

L1 정규화를 하고 다시 유클리디언 유사도를 측정

In [8]:
import numpy as np 

def l1_normalize(v):
  norm = np.sum(v)
  return v / norm 

tfidf_norm_l1 = l1_normalize(tfidf_matrix)
euclidean_distances(tfidf_norm_l1[0:1], tfidf_norm_l1[1:2])

array([[0.21243357]])

맨하탄 유사도 측정으로 첫 번째와 두 번째 문장 비교

In [9]:
from sklearn.metrics.pairwise import manhattan_distances

manhattan_distances(tfidf_norm_l1[0:1], tfidf_norm_l1[1:2])

array([[0.85654185]])